spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/pureenergy/dev/movie/**
          filters:
            - RewritePath=/pureenergy/dev/movie/(?<segment>.*),/$\{segment}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/pureenergy/dev/comment/**
          filters:
            - RewritePath=/pureenergy/dev/comment/(?<segment>.*),/$\{segment}
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/pureenergy/dev/reservation/**
          filters:
            - RewritePath=/pureenergy/dev/reservation/(?<segment>.*),/$\{segment}
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/pureenergy/dev/log/**
          filters:
            - RewritePath=/pureenergy/dev/log/(?<segment>.*),/$\{segment}



server:
  port: 8762

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Case Study Microservices
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'

